openapi: 3.0.4
info:
  title: Swagger API GATEWAY - OpenAPI 3.0
  description: |-
   This is a simple API Gateway for demonstration puposes
  termsOfService: https://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12

servers:
  - url: http://localhost:5000
tags:
  - name: user
    description: Operations about user
paths:
  /login:
    post:
      tags:
        - user
      summary: Logs user into the system.
      description: Log into the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: "opcUser"
                password:
                  type: string
                  example: "opcUser123"
     
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
                    example: "Welcome opcUser!"
                  status:
                    type: string
                    example: success
                  token:
                    type: string
                    example: 123456
                  
        '401':
          description: Invalid username/password supplied
          content:
            application/json:
              schema:
                type: object
                properties:   
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: "Invalid credentials"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session.
      description: Log user out of the system.
      operationId: logoutUser
      parameters: []
      responses:
        '200':
          description: successful operation
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  
    
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      required:
        - status
        - message
