openapi: 3.0.4
info:
  title: Swagger API GATEWAY - OpenAPI 3.0
  description: |-
   This is a simple API Gateway for demonstration puposes
  termsOfService: https://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12

servers:
  - url: http://localhost:8080
tags:
  - name: user
    description: Operations about user
paths:
  /login:
    post:
      tags:
        - user
      summary: Logs user into the system.
      description: Log into the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
     
      responses:
        '200':
          description: Successfully logged in
          
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Invalid username/password supplied
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session.
      description: Log user out of the system.
      operationId: logoutUser
      parameters: []
      responses:
        '200':
          description: successful operation
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  
    
    
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        petId:
          type: integer
          format: int64
          example: 198772
        quantity:
          type: integer
          format: int32
          example: 7
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
      xml:
        name: order

    User:
      type: object
      properties:
        username:
          type: string
          example: 'opcUser123'
        password:
          type: string
          example: '12345'

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  requestBodies:
   
 
      in: header